version: 0.2

phases:
    install:
        runtime-versions:
            golang: 1.12
        commands:
            - echo Installation Started
            - go -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip

    build:
        commands:
            # Build our go application
            - echo build go project
            - go build -o main

            # zip go app
            - echo zip go project
            - zip main.zip main
            - ls
            - ~\Go\Bin\build-lambda-zip.exe -o main.zip main

artifacts:
    type: zip
    files:
        - packaged.yml
