version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: 'simulate'

phases:
    install:
        runtime-versions:
            golang: 1.12
        commands:
            - echo Installation Started
            - export GOPATH=$(pwd)/..
            - go get -v github.com/montanaflynn/stats
            - go get -v  -u gonum.org/v1/gonum/...
            - go get -v -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip

    build:
        commands:
             #moving files in sampler
            - mkdir sampler
            - mv * sampler || true
            - cd sampler
            # Build our go application
            - echo build go project
            - ls 
            - pwd
            - go build -o main

            # zip go app
            - echo zip go project
            - zip -j main.zip main
            - ls
            - echo updating lambda function
            - aws lambda update-function-code --function-name simulate --zip-file fileb://main.zip

artifacts:
    type: zip
    files:
        - '**/*'
