version: 0.2

phases:
    install:
        runtime-versions:
            golang: 1.12
        commands:
            - echo Installation Started
            - go get github.com/montanaflynn/stats
            - go get -u gonum.org/v1/gonum/...
            - go get -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip

    build:
        commands:
            # Build our go application
            - echo build go project
            - go build -o main

            # zip go app
            - echo zip go project
            - zip main.zip main
            - ls

    post_build:
        commands:
            # update function
            - echo updating lambda function
            - aws s3 cp main.zip s3://simulate/main.zip
            - aws lambda update-function-code --function-name simulate --s3-bucket simulate --s3-key main.zip --publish

artifacts:
    type: zip
    files:
        - packaged.yml
